# serializers.py
from rest_framework import serializers
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.utils import timezone
from datetime import timedelta
import random
import string
from .models import OTP, Personalization
from .utils import validate_and_get_otp

User = get_user_model()

class SignupSerializer(serializers.Serializer):
    email = serializers.EmailField()
    name = serializers.CharField(max_length=150)
    password = serializers.CharField(write_only=True, min_length=8)
    
    def validate_email(self, value):
        value = value.lower().strip()#makes email lowercase and removes spaces.
        verified_user = User.objects.filter(email=value, verified=True).exists()#.filter() returns a QuerySet, not a True/False value.
        #.exists() is used to check if any record matches (returns True or False).

        if verified_user:
            raise serializers.ValidationError("This email is already registered.")
        return value
    
    # def validate_name(self, value):
    #     return value.strip()
    
    def create(self, validated_data):
        email = validated_data['email']
        
        # It removes old unverified accounts with the same email before creating a new one.
        User.objects.filter(email=email, verified=False).delete()
        
        # Create new user
        user = User.objects.create_user(
            username=email,
            email=email,
            first_name=validated_data['name'],
            password=validated_data['password'],
            verified=False
        )
        
        # Generate and send OTP
        otp_code = ''.join(random.choices(string.digits, k=6))
        '''
        Generates a 6-digit random OTP made of numbers.
        string.digits = '0123456789'
        random.choices(..., k=6) → picks 6 random digits.
        .join(...) → combines them into a single string like '483920'.
        '''
        expires_at = timezone.now() + timedelta(minutes=10)

        #Deletes any previous unused OTPs for that email before sending a new on
        OTP.objects.filter(email=email, is_used=False).delete()
        OTP.objects.create(
            email=email,
            otp_code=otp_code,
            expires_at=expires_at
        )
        
        self.send_otp_email(email, otp_code)
        
        return user
    
    
    '''
    ❓From where this 'validated_data' comes in the line def create(self, validated_data)?
    Ans:
    When DRF serializer’s .is_valid() runs successfully, it stores cleaned input data in validated_data.
    DRF automatically passes this dictionary into the create() method when .save() is called.
    👉 In short: validated_data = all the valid fields from the user’s request (after passing validation).
    
    '''


    '''
    ❓Why @staticmethod for send_otp_email?
    Ans:
    @staticmethod: Means the method doesn't need access to self (the serializer instance),or any instance data. It's a utility function that can work independently
    Use case: The method only uses the parameters passed to it (email and otp_code)

    ❓why I can use a independant function like send_otp_email in this case

    🔴email and otp_code are generated by your system inside the create() method — not sent by the user.
    🔴Since send_otp_email() just uses those values to send an email, it doesn’t need anything from the serializer instance (self).
    🔴That’s why it can be a @staticmethod — it works independently of the serializer object.
    '''
    @staticmethod
    def send_otp_email(email, otp_code):
        subject = "Your Verification Code – Dalil AI Tourist Guide"
        message = f"""Dear User,

Thank you for registering with Dalil – Your Smart AI Travel Guide.

Your One-Time Password (OTP) for email verification is:

        {otp_code}

This code is valid for 10 minutes. Please do not share it with anyone for security reasons.

If you did not create an account with Dalil, please ignore this email or contact our support team immediately.

Best regards,
The Dalil Team
support@dalil-nl.cloud"""
        send_mail(subject, message, 'noreply@yourdomain.com', [email])


class VerifyOTPSerializer(serializers.Serializer):
    email = serializers.EmailField()
    otp_code = serializers.CharField(max_length=6)
    
    def validate(self, data):
        email = data['email'].lower().strip()
        otp_code = data['otp_code'].strip()
        
        # try:
        #     otp = OTP.objects.filter(email=email, is_used=False).latest('created_at')
        # except OTP.DoesNotExist:
        #     raise serializers.ValidationError("No valid OTP found for this email.")
        
        # if not otp.is_valid():
        #     raise serializers.ValidationError("OTP has expired.")
        
        # if otp.otp_code != otp_code:
        #     raise serializers.ValidationError("Invalid OTP code.")
        otp = validate_and_get_otp(email, otp_code)  # 👈 call the function here

        data['otp'] = otp
        return data


class ResendOTPSerializer(serializers.Serializer):
    email = serializers.EmailField()
    
    def validate_email(self, value):
        value = value.lower().strip()
        user = User.objects.filter(email=value, verified=False).exists()
        if not user:
            raise serializers.ValidationError("This Email Already Verified")
        return value


class LoginSerializer(serializers.Serializer):
    email = serializers.EmailField()
    password = serializers.CharField(write_only=True)
    
    def validate(self, data):
        email = data['email'].lower().strip()
        password = data['password']
        
        try:
            user = User.objects.get(email=email, verified=True)
        except User.DoesNotExist:
            raise serializers.ValidationError("Invalid email")
        
        if not user.check_password(password):#if the password enterd by the user is not correct 
            raise serializers.ValidationError("Invalid password.")
        
        data['user'] = user
        return data


class ForgotPasswordSerializer(serializers.Serializer):
    email = serializers.EmailField()
    
    def validate_email(self, value):
        value = value.lower().strip()
        user = User.objects.filter(email=value, verified=True).exists()
        if not user:
            raise serializers.ValidationError("Email not found or not verified.")
        return value


class ResetPasswordSerializer(serializers.Serializer):
    # email = serializers.EmailField()
    # otp_code = serializers.CharField(max_length=6)
    uid = serializers.CharField()
    token = serializers.CharField()
    new_password = serializers.CharField(write_only=True, min_length=8)
    confirm_password = serializers.CharField(write_only=True, min_length=8)
    '''
    uid and token come from the reset link URL, not from the input fields.
    You type only new_password and confirm_password.
    Browser auto-extracts uid and token from URL.
    Serializer requires all 4 fields because backend needs uid + token to identify user and verify reset link.
    '''


class UserProfileSerializer(serializers.ModelSerializer):
    name = serializers.CharField(source='first_name', required=False, allow_blank=True)
    profile_image_url = serializers.SerializerMethodField(read_only=True)

    class Meta:
        model = User
        fields = ['id', 'email', 'name', 'profile_image', 'profile_image_url', 'verified', 'created_at']
        read_only_fields = ['id', 'email', 'verified', 'created_at']

    def get_profile_image_url(self, obj):
        request = self.context.get('request')
        if obj.profile_image and request:
            return request.build_absolute_uri(obj.profile_image.url)
        return None


class PersonalizationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Personalization
        fields = ['id', 'surface_area', 'fruit_tress', 'fruit_tree_types', 'created_at', 'updated_at']
        read_only_fields = ['id', 'created_at', 'updated_at']
    
    # def validate(self, data):
    #     email = data['email'].lower().strip()
    #     otp_code = data['otp_code'].strip()
        
    #     # try:
    #     #     otp = OTP.objects.filter(email=email, is_used=False).latest('created_at')
    #     # except OTP.DoesNotExist:
    #     #     raise serializers.ValidationError("No valid OTP found for this email.")
        
    #     # if not otp.is_valid():
    #     #     raise serializers.ValidationError("OTP has expired.")
        
    #     # if otp.otp_code != otp_code:
    #     #     raise serializers.ValidationError("Invalid OTP code.")
    #     otp = validate_and_get_otp(email, otp_code)  # 👈 call the function here      
    #     data['otp'] = otp
    #     return data


















