# renew_before_expiry = 30 days
version = 2.10.0
archive_dir = /etc/letsencrypt/archive/prooning.com
cert = /etc/letsencrypt/live/prooning.com/cert.pem
privkey = /etc/letsencrypt/live/prooning.com/privkey.pem
chain = /etc/letsencrypt/live/prooning.com/chain.pem
fullchain = /etc/letsencrypt/live/prooning.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 762c5fe464564f91304f27dc4a61e030
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
prooning.com = /var/www/certbot
www.prooning.com = /var/www/certbot
