# Generated by Django 4.2.30 on 2026-04-11 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_key",
                    models.CharField(
                        help_text="Must match exactly what labels.txt contains",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(blank=True, max_length=200)),
                ("icon_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "accuracy",
                    models.FloatField(default=98.9, help_text="Model accuracy percent"),
                ),
                (
                    "latency_ms",
                    models.IntegerField(
                        default=15, help_text="Inference latency in ms"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Plant Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScanHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("lite", "Lite (Local)"), ("pro", "Pro (Global)")],
                        max_length=10,
                    ),
                ),
                ("detected_label", models.CharField(max_length=100)),
                ("confidence", models.FloatField(default=0.0)),
                ("ripeness_score", models.IntegerField(default=0)),
                ("ripeness_label", models.CharField(blank=True, max_length=50)),
                ("peak_window", models.CharField(blank=True, max_length=200)),
                ("detection_detail", models.TextField(blank=True)),
                ("quick_tips", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Scan History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ripeness_score",
                    models.IntegerField(
                        default=0,
                        help_text="0–100 ripeness/readiness percent shown on the result card",
                    ),
                ),
                (
                    "ripeness_label",
                    models.CharField(
                        default="Unknown",
                        help_text="e.g. Low / Medium / High / Very High",
                        max_length=50,
                    ),
                ),
                (
                    "peak_window",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Harvest within 3–5 days"',
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Classified", "Classified"),
                            ("Unclassified", "Unclassified"),
                        ],
                        default="Classified",
                        max_length=20,
                    ),
                ),
                (
                    "quick_tips",
                    models.JSONField(
                        default=list,
                        help_text="Short actionable tips shown as bullet list on result card",
                    ),
                ),
                (
                    "detection_detail",
                    models.TextField(
                        help_text="Detailed paragraph shown under Detection Detail section"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list,
                        help_text="More Recommendations section on result card",
                    ),
                ),
                ("reference_image_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule",
                        to="api.detectionlabel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detectionlabel",
            name="plant_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="api.plantcategory",
            ),
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("lite", "Lite (Local)"), ("pro", "Pro (Global)")],
                        max_length=10,
                    ),
                ),
                ("context_label", models.CharField(blank=True, max_length=100)),
                (
                    "context_data",
                    models.JSONField(
                        default=dict,
                        help_text="Serialized detection result injected as AI context",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_session",
                        to="api.scanhistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
