# Generated by Django 4.2.30 on 2026-04-13 03:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFLiteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text='Semantic version string, e.g. "v1.0.0". Must be unique across all releases.',
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "model_file",
                    models.FileField(
                        help_text="Upload the .tflite model file here. It will be served at a stable URL.",
                        upload_to=api.models._tflite_upload_path,
                    ),
                ),
                (
                    "labels_file",
                    models.FileField(
                        help_text="Upload the labels.txt file that pairs with this model.",
                        upload_to=api.models._tflite_upload_path,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Mark this release as the one served to Flutter clients. Only ONE release should be active at a time. Activating this record deactivates all others automatically.",
                    ),
                ),
                (
                    "changelog",
                    models.TextField(
                        blank=True,
                        help_text="Optional release notes / description of what changed in this model version.",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "TFLite Model Release",
                "verbose_name_plural": "TFLite Model Releases",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
