# Generated by Django 5.2.13 on 2026-05-06 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_tflite_model_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlabel',
            name='plant_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.plantcategory'),
        ),
    ]
